server {
    # Escuta na porta 80 (HTTP)
    listen 80;
    server_name localhost;

    # Diretório base onde o servidor web procura pelos arquivos
    root /var/www/begods;
    
    # Arquivo principal
    index index.html;

    # Configuração de logs personalizados
    access_log /var/log/nginx/begods_access.log;
    error_log /var/log/nginx/begods_error.log;

    # Configuração da página 404 customizada
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    # Tratamento das requisições
    location / {
        try_files $uri $uri/ =404;
    }
}
