events {
    # Define o número máximo de conexões simultâneas que o Nginx consegue gerir
    worker_connections 1024;
}

http {
    server {
        # O Nginx vai "ouvir" na porta 80 (a porta padrão da internet)
        listen 80;

        # 1. Rota do Frontend: Tudo o que for para a raiz (/) vai para o container do frontend
        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Rota do Backend (API): Tudo o que começar com /api vai para o container do backend
        location /api/ {
            proxy_pass http://backend:5000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        # 3. Rota de Healthcheck: Apenas para verificar se a API está viva
        location /health {
            proxy_pass http://backend:5000/health;
        }
    }
}